name: 'Build c++ project'
description: 'Build c++ project with help cmake'
author: nicledomaS
branding:
  color: black
  icon: terminal
inputs:
  srcdir:
    description: 'C++ source code (if other than root)'
    required: false
    default: ''
  submodule_update:
    description: 'Git submodule update'
    required: false
    default: 'OFF'
  cmake_args:
    description: 'Cmake args (example -D<ARG1>=value;-D<ARG1>=value)'
    required: false
    default: ''
  run_tests:
    description: 'Run unit tests'
    required: false
    default: 'OFF'
  unit_test_build:
    description: 'Cmake arg for turn build unit test (if need)'
    required: false
    default: ''
  create_package:
    description: 'Create package'
    required: false
    default: 'OFF'
  package_generator:
    description: 'Package generator'
    required: false   
    default: 'TGZ'
  config:
    description: 'For multi-configuration tools, choose configuration <Release or Debug>'
    required: false
    default: 'Release'
runs:
  using: 'node12'
  main: 'dist/index.js'
